#!/bin/bash
# entrypoints/target-init.sh

echo "Starting target container SSH initialization..."

# Wait for the public key to be generated by the control node
while [ ! -f /ssh-shared/authorized_keys ]; do
  echo "Waiting for SSH keys to be generated by ansible-control container..."
  sleep 2
done

# Set up authorized keys for the ansible user
mkdir -p /home/ansible/.ssh
cp /ssh-shared/authorized_keys /home/ansible/.ssh/authorized_keys
chown -R ansible:ansible /home/ansible/.ssh
chmod 700 /home/ansible/.ssh
chmod 600 /home/ansible/.ssh/authorized_keys

echo "SSH keys authorized successfully."

# Generate host keys if they don't exist (needed for Rocky/other distros)
ssh-keygen -A

# Start the SSH daemon in foreground mode
exec /usr/sbin/sshd -D
