[targets]
target-ubuntu-1 ansible_host=172.25.0.21 ansible_user=ansible
target-ubuntu-2 ansible_host=172.25.0.22 ansible_user=ansible
target-debian-1 ansible_host=172.25.0.23 ansible_user=ansible
target-rocky-1 ansible_host=172.25.0.24 ansible_user=ansible

[targets:vars]
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root
